### ISSUE TITLE
VUSELabeler.py - AttributeError: 'module' object has no attribute 'YOLO'

### ISSUE THREAD

**Issue by Arsey** [stanford-futuredata/noscope#21]
When I run `python VUSELabeler.py --yolo_dir /path/to/darkflow --output_csv_fname /path/to/output.csv --input_video_fname /path/to/output.avi --start_from 0` it throws an error:

```Python
Using TensorFlow backend.
Traceback (most recent call last):
  File "VUSELabeler.py", line 85, in <module>
    main()
  File "VUSELabeler.py", line 79, in main
    args.yolo_dir, args.start_from)
  File "VUSELabeler.py", line 38, in label_video
    yolo_dir + '/cfg/coco.data')
  File "VUSELabeler.py", line 15, in __init__
    self.YOLO = noscope.YOLO(config_filename, weights_filename, data_config)
AttributeError: 'module' object has no attribute 'YOLO'
```

**Comment by ddkang** [comment]
Apologies - this has been deprecated in favor of yolo_standalone: https://github.com/ddkang/darknet/tree/yolo_standalone
